package:
  name: helios-menuinst
  version: "0.2.5"

source:
  path: src

build:
  noarch: generic
  number: 0
  script:
    - mkdir -p {{ PREFIX }}/Menu
    - cp {{ SRC_DIR }}/3dgeo.ico {{ PREFIX }}/Menu/3dgeo.ico
    - cp {{ SRC_DIR }}/3dgeo.png {{ PREFIX }}/Menu/3dgeo.png
    - cp {{ SRC_DIR }}/menu.json {{ PREFIX }}/Menu/helios-menuinst.json

requirements:
  run:
    - jupyterlab

test:
  commands:
    - test -f $PREFIX/Menu/helios-menuinst.json
    - test -f $PREFIX/Menu/3dgeo.ico
    - test -f $PREFIX/Menu/3dgeo.png

about:
  home: https://github.com/3dgeo-heidelberg/helios
  summary: 'Menu items for Helios++'
  description: |
    HELIOS++ is a general-purpose software package for simulation of terrestrial,
    mobile and airborne laser scanning surveys written in C++11. It is developed
    and maintained by the 3DGeo Research Group at Heidelberg University. This
    package adds the menu items for the Helios++ constructor installers.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - dokempf
